### Basic request
GET http://localhost:5005/api

### Get All Users
GET http://localhost:5005/api/user
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJpdm9AbWFpbC5uZXQiLCJpYXQiOjE1ODMzNTk2NTEsImF1ZCI6InNjb3BlOnNldHVwIiwiaXNzIjoidXNyIn0.Z9Kr50sTyuznMCsvG5G6YjjwrFRDyIVfwCoKq5Nt9uk


